### ISSUE TITLE
nut 到底是个什么东西？

### ISSUE THREAD

**Issue by kybetter** [nut-project/nut#67]
看示例，得知它是一个前端框架带有 UI。

你们还说它是一个微前端框架，为啥又有 markdown？集成进来做什么？文档里面又什么也没写。

到底是微前端还是前端？还是定义成一个大而全的包罗万象的东西？

麻烦大佬解惑。

**Comment by fengzilong** [comment]
![materials](https://user-images.githubusercontent.com/9125255/67834564-ab206e80-fb22-11e9-8752-eccfbb27e09a.gif)

https://github.com/nut-project/nut/blob/master/plugins/pages/materials/lib/index.js

这是最近在写的 `物料` 插件初版，可以先预览下

**Comment by kybetter** [comment]
物料插件功能很赞啊！期待。
如果有文档的话，我也想参与开发呢。😁

**Comment by fengzilong** [comment]
哈哈正好缺人呢，我邀请你了，文档后面会有的 😎
